### ISSUE TITLE
Huawei P9/M3 Xperia Z4で正常に動作しない

### ISSUE THREAD

**Issue by MakotiaFrontia** [Siketyan/SilicaGel-for-CloudPlayer#1]
Huawei端末においてはアプリを起動しているがツイートがされない、 Xperiaでは曲が切り替わった瞬間このアプリが落ちるという状態になっている

P.S.ほかの端末でもテストしてみる

**Comment by Siketyan** [comment]
新バージョンで動作確認できたためクローズ
